# Generated by Django 5.0.1 on 2024-03-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='corpo',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to='projeto.chat'),
        ),
    ]
